[package]
name = "grpc-app-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
x509-parser = { workspace = true }
anyhow = { workspace = true }
authn-scope-workload = { path = "../../libs/rust-libs/authn-scope-workload" }
rustls-pemfile = { workspace = true }
tonic = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-build = { workspace = true }
