[package]
name    = "authn-scope-tpm"
version = "0.1.0"
edition = "2021"

[dependencies]
tss-esapi  = { workspace = true }
serde      = { workspace = true }
serde_json = { workspace = true }
ring       = { workspace = true }
anyhow     = { workspace = true }
tracing    = { workspace = true }
thiserror  = { workspace = true }
base64     = { workspace = true }
